version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2013
environment:
  QT32PATH: C:\Qt\5.6\msvc2013
  QT64PATH: C:\Qt\5.6\msvc2013_64
  matrix:
  - BITS: 64
  - BITS: 32
build_script:
- cmd: build.bat %BITS%
test: off
artifacts:
- path: build%BITS%\MeddleGit%BITS%
  name: MeddleGit%BITS%