language: cpp

cache: ccache

notifications:
  email: false

branches:
  only:
  - master

matrix:
  include:
  - os: osx
    env: BUILD_COMMAND="qmake ../src && make -j4" DEPLOY=1
  - os: linux
    env: BUILD_COMMAND="qmake PREFIX=/usr APPIMAGE=1 ../src && make -j4" DEPLOY=1

sudo: required
dist: trusty

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y &&
      sudo apt-get update -qq
    ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install p7zip ccache qt5 &&
      export PATH="/usr/local/opt/qt/bin:$PATH"
    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -y install qt56base qt56svg --allow-unauthenticated &&
      source /opt/qt5*/bin/qt5*-env.sh
    ; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      macdeployqt MeddleGit.app -dmg &&
      export FILE_TO_UPLOAD="MeddleGit.dmg"
    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo make INSTALL_ROOT=appdir install &&
        sudo chown -R $USER appdir &&
        wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" &&
        chmod a+x linuxdeployqt*.AppImage &&
        unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH &&
        ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -verbose=2 &&
        ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -verbose=2 &&
        find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq &&
        export FILE_TO_UPLOAD="MeddleGit-x86_64.AppImage"
    ; fi

script:
  - mkdir build
  - cd build
  - (eval "$BUILD_COMMAND")